#!/usr/bin/python3

def raise_exception():
    int = "9"
    print(9 + int)
